version: '3.8'

services:
  backend:
    build: ./backend
    container_name: deepfake-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./forgery_detection_app  
    container_name: deepfake-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
